language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 5e02fc0469ded2fa009a3e6051c8f25accb84df8
  keep-history: true
  on:
    branch: master
  local-dir: dist
  repo: https://github.com/voyagerwoo/voyagerwoo.github.io