language: node_js

node_js:
  - "7"

cache:
  directories:
    - node_modules

before_script:
  - npm install
  - npm run build

script:
# enable error reporting to the console
  - set -e
# cleanup ".gh_dist"
  - rm -rf .gh_dist
  - mkdir .gh_dist
# clone remote repo to "_site"
  - git clone https://voyagerwoo:${GH_TOKEN}@github.com/voyagerwoo/$GH_PAGE_REPO.git --branch master .gh_dist
# dist into ".gh_dist"
  - cp -r dist/* .gh_dist/
# push
  - cd .gh_dist
  - git config user.email "voyagerwoo@gmail.com"
  - git config user.name "voyagerwoo"
  - git add --all
  - git commit -a -m "Travis \#$TRAVIS_BUILD_NUMBER"
  - git push --force origin master
