language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: dist
  repo: $GH_PAGE_REPO
  on:
    branch: master